### ISSUE TITLE
Towards v1.0

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#148]
I am mopping up the last issues required for the v1.0 release 🚀 

This would be the time to discuss API changes if there is something we are still not sure about. 

# Feliz issues
I would like to fix these issues in Feliz before going stable
 - [x] [Clean up memo overloads](https://github.com/Zaid-Ajaj/Feliz/issues/118)
 - [x] [Add KeyboardEvent goodness to easily bind to key press events](https://github.com/Zaid-Ajaj/Feliz/issues/93)
 - [x] [Finish React API bindings](https://github.com/Zaid-Ajaj/Feliz/issues/127)
 - [x] [Review prop.ref API implementation and add examples](https://github.com/Zaid-Ajaj/Feliz/issues/147)
 - [x] [Finish React hook bindings](https://github.com/Zaid-Ajaj/Feliz/issues/50)
 - [x] [Finish SVG element and attribute bindings](https://github.com/Zaid-Ajaj/Feliz/issues/184)

# Ecosystem

I already bumped Feliz bindings to v1.0 like Recharts, PigeonMaps, Popover and the template. I would like to get [Feliz.MaterialUI](https://github.com/cmeeren/Feliz.MaterialUI) to stable version as well cc @cmeeren. Same for [Feliz.Plotly](https://github.com/Shmew/Feliz.Plotly) cc @Shmew 

- [x] Stable Feliz.MaterialUI
- [x] Stable Feliz.Plotly 

# Final nice to haves

I would really appreciate it if we could also work on [Feliz.AntDesign](https://github.com/Zaid-Ajaj/Feliz.AntDesign) and get it into a nice form for the the stable release thought it will require a lot of work. Not a blocker for Feliz v1.0 but would be great to have along with the other ecosystem libraries.

**Comment by Shmew** [comment]
I'll try to carve out some time to go over some of the things I still have on my to-do list for [Feliz.Plotly](https://github.com/Shmew/Feliz.Plotly). 

I've been keeping my projects [Feliz.SweetAlert](https://github.com/Shmew/Feliz.SweetAlert), [Feliz.MaterialUI.MaterialTable](https://github.com/Shmew/Feliz.MaterialUI.MaterialTable), and [Feliz.MaterialUI.Pickers](https://github.com/Shmew/Feliz.MaterialUI.Pickers) up to date as the source libraries have pushed out new updates and I think those three are ready to go for the most part.

I've been working on an application for work using all of these projects as well as [Feliz.MaterialUI](https://github.com/cmeeren/Feliz.MaterialUI) so I think all the major issues have been found and fixed at this point.

**Comment by Shmew** [comment]
Well I've had a quite a bit of time this past week, so I dumped a lot of that into finishing up [Feliz.Plotly](https://github.com/Shmew/Feliz.Plotly). I'm happy to say that every plot type and feature is now implemented with examples. So it should be ready to roll!

**Comment by Zaid-Ajaj** [comment]
Awesome stuff @Shmew! This means both Plotly and Mui are pretty much stable at this point 🥰 looks like we are getting there, I will try to work out the prop ref API this weekend as well

**Comment by adelarsq** [comment]
@Zaid-Ajaj So are there plans to release the version 1.0 now that this issue is closed?

**Comment by Zaid-Ajaj** [comment]
@adelarsq Oops it looks like this was closed by accident as a result of closing issue #188 😅 I publish the v1.0 release very soon after merging #189 and writing a short blog post on Fable's blog

**Comment by adelarsq** [comment]
Oh right. I was confused about what was missing. Thanks @Zaid-Ajaj
I'm already using and pretty feliz (happy in portuguese) with Feliz 😄

**Comment by Zaid-Ajaj** [comment]
@adelarsq Feliz has just released the v1.0 package :fire: :rocket: :tada:

**Comment by adelarsq** [comment]
Good news!
Thanks @Zaid-Ajaj and everyone involved. 🚀
